tasks:
  tests:
    - python m.py
  after_success:
    - git config --global user.name "semantic-release"
    - git config --global user.email "semantic-release@frigg"
    - pip3 install python-semantic-release
    - git checkout master
    - semantic-release publish
